"""Platform-specific configuration for account selection flows."""

PLATFORM_CONFIG = {
    "google": {
        "parent_id_field": "loginCustomerId",
        "account_id_field": "customerId",
        "parent_label": "manager account",
        "account_label": "customer account",
        "fetch_parents": "fetch_mcc_accounts",
        "fetch_children": "fetch_customer_accounts",
        "progress_find": "Finding your Google Ads accounts",
        "progress_select_parent": "Selecting Google manager account",
        "progress_load_children": "Loading Google customer accounts",
        "progress_select_account": "Selecting Google customer account",
        "summary_fields": [
            ("loginCustomerId", "Manager account"),
            ("customerId", "Customer account"),
        ],
        "required_fields": [
            "businessName",
            "websiteURL",
            "budget",
            "durationDays",
            "platform",
            "loginCustomerId",
            "customerId",
        ],
    },
    "meta": {
        "parent_id_field": "metaBusinessId",
        "fb_page_id_field": "fbPageId",
        "ig_page_id_field": "igPageId",
        "account_id_field": "metaAdAccountId",
        "pixel_id_field": "metaPixelId",
        "parent_label": "business account",
        "fb_page_label": "Facebook page",
        "ig_page_label": "Instagram account",
        "account_label": "ad account",
        "pixel_label": "Meta pixel",
        "fetch_parents": "fetch_meta_business_accounts",
        "fetch_fb_pages": "fetch_fb_pages",
        "fetch_ig_accounts": "fetch_ig_accounts",
        "fetch_children": "fetch_meta_ad_accounts",
        "fetch_pixels": "fetch_pixels",
        "progress_find": "Finding your Meta business accounts",
        "progress_select_parent": "Selecting Meta business account",
        "progress_load_fb_pages": "Loading Facebook pages",
        "progress_select_fb_page": "Selecting Facebook page",
        "progress_load_ig_accounts": "Loading Instagram accounts",
        "progress_select_ig_account": "Selecting Instagram account",
        "progress_load_children": "Loading Meta ad accounts",
        "progress_select_account": "Selecting Meta ad account",
        "progress_load_pixels": "Loading Meta pixels",
        "progress_select_pixel": "Selecting Meta pixel",
        "summary_fields": [
            ("metaBusinessId", "Business account"),
            ("metaAdAccountId", "Ad account"),
            ("fbPageId", "Facebook page"),
            ("igPageId", "Instagram account"),
            ("metaPixelId", "Meta pixel"),
        ],
        "required_fields": [
            "businessName",
            "websiteURL",
            "budget",
            "durationDays",
            "platform",
            "metaBusinessId",
            "fbPageId",
            "igPageId",
            "metaAdAccountId",
            "metaPixelId",
        ],
    },
}


def all_fields_collected(ad_plan: dict, config: dict) -> bool:
    """Check if all required fields are present in the ad plan."""
    return all(field in ad_plan for field in config["required_fields"])
